server:
  port: 8080

spring:
  ncp:
    storage:
      endpoint: kr.object.ncloudstorage.com
      access-key: ncp_iam_BPAMKR2dR61euJgtiu8t
      secret-key: ncp_iam_BPKMKR3p8VvwtfRpkH7B4ejaJc5sHOQuUa
      bucket-name: profile-img
  datasource:
    url: jdbc:mysql://223.130.152.205:3306/test
    username: test
    password: gjgj1234!
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    show-sql: true
    generate-ddl: true
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL8Dialect
        format_sql: true
        default_batch_fetch_size: 100
    logging.level:
      org.hibernate.SQL: debug
  data:
    redis:
      host: localhost
      port: 6379
  servlet:
    multipart:
      enabled: true
      max-file-size: 10MB
      max-request-size: 100MB
  mail:
    host: smtp.gmail.com
    port: 587
    username: gwanilgim632@gmail.com
    password: qvmq rrrh ofpi pszf
    properties:
      mail:
        smtp:
          auth: true
          timeout: 5000
          starttls:
            enable: true
            required: true
      auth-code-expiration-millis: 180000
  security:
    oauth2:
      client:
        registration:
          google:
            client-id: Ov23liTSgkfs6uUSbMgz
            client-secret: 8450266fd4d4c69a004d7b4f77e07c72106682d9
            scope: profile, email
          naver:
            client-id: 81vPZsOtd5LfziPCt08f
            client-secret: X4YY0wPOCl
            client-authentication-method: client_secret_post
            authorization-grant-type: authorization_code
            redirect-uri: "{baseUrl}/{action}/oauth2/code/{registrationId}"
            scope:
              - name
              - email
              - profile_image
              - nickname
            client-name: Naver
          kakao:
            client-id: 0d07280765931398b208f0ebc7226a1c #실제 배포시 테스트 앱용이 아닌 실제 앱 키 사용해야함 시크릿 키도 동일
            client-secret: rPjx7m1TB4FLVjgENFkT1kn9OqC5v5VG
            client-authentication-method: client_secret_post
            authorization-grant-type: authorization_code
            scope:
              - name
              - profile_nickname
              - profile_image
              - account_email
            redirect-uri: "{baseUrl}/{action}/oauth2/code/{registrationId}"
            client-name: Kakao
        provider:
          naver:
            authorization-uri: https://nid.naver.com/oauth2.0/authorize
            token-uri: https://nid.naver.com/oauth2.0/token
            user-info-uri: https://openapi.naver.com/v1/nid/me
            user-info-authentication-method: header
            user-name-attribute: response
          kakao:
            authorization-uri: https://kauth.kakao.com/oauth/authorize
            token-uri: https://kauth.kakao.com/oauth/token
            user-info-uri: https://kapi.kakao.com/v2/user/me
            user-info-authentication-method: header
            user-name-attribute: id


jwt:
  secret_key: ecaca4cdf504d2c8932ab357e24fa96c35df490f57b313406a147de4cefb5f4d10511b2c60ddb21bdddc0eb8f0b1af175598a31ab9d4c834d9d24989c54c3147
  access_token_expire: 10800000 #3h
  refresh_token_expire: 604800000 #7d
