name: Build and Deploy

on:
  push:
    branches:
      - 배포  # main으로 수정예정

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Java 17
        uses: actions/setup-java@v2
        with:
          java-version: '17'
          distribution: 'zulu'

      - name: Build with Gradle
        run: ./gradlew build

      - name: Deploy to NCP
        env:
          SERVER_IP: ${{ secrets.SERVER_IP }}
          USERNAME: ${{ secrets.SERVER_USERNAME }}
          PRIVATE_KEY: ${{ secrets.NCP_PRIVATE_KEY }}
        run: |
          # JAR 파일을 NCP 서버로 복사
          scp -i $PRIVATE_KEY build/libs/GGJ_BE-0.0.1-SNAPSHOT.jar $USERNAME@$SERVER_IP:/home/ubuntu/app/build/libs/
          
          # JAR 파일 실행
          ssh -i $PRIVATE_KEY $USERNAME@$SERVER_IP "java -jar /home/ubuntu/app/build/libs/GGJ_BE-0.0.1-SNAPSHOT.jar"
